SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0ZWx6ZnRhbXZ6Y3F4ZWpjcXNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTk1MDMsImV4cCI6MjA3MTE3NTUwM30.ZaAHgNNoQaPEDdRucSLC1BWdx7Nw7eRUFmk_IVj2tVw"
SUPABASE_URL = "https://rtelzftamvzcqxejcqsr.supabase.co"
GOOGLE_API_KEY = "AIzaSyDHhwGi-xGxN26PsLQhibDZeVvmCHBuJ6Q"
COHERE_API_KEY = "KlACkDwaV2satoyutL1v5aK5Gs4vYxAT8dWXksVF"
ADMIN_EMAIL = "duy.bk1608@gmail.com"
ADMIN_PASSWORD = "admin1234"